apiVersion: ddapr.io/v1alpha1
kind: Component
metadata:
  name: shopstate
spec:
  type: state.azure.statestore
  version: v1
  metadata:
  - name: accountName
    value: "globoticketstate"
  - name: accountKey
    secretkeyref:
      name: blob-secret
      key: account-key
  - name: containerName
    value: "statestore"
auth:
  secretStore: kubernetes
